version: '3'

services:
  supermarketapi:
    build: .
    command: make run
    volumes:
      - .:/var/www/supermarket_api
      - bundle-data:/var/www/bundle
    ports:
      - "3000:3000"
    depends_on:
      - postgresdb

  postgresdb:
    image: postgres:9.6
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  swaggereditor:
    image: swaggerapi/swagger-editor
    ports:
      - "8080:8080"

volumes:
  postgres-data:
    driver: local
  bundle-data:
    driver: local
