
# default: &default
#   adapter: postgresql
#   encoding: unicode
#   # For details on connection pooling, see Rails configuration guide
#   # http://guides.rubyonrails.org/configuring.html#database-pooling
#   pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
#   host: <%= ENV['DBHOST'] %>
#   username: <%= ENV['DBUSER'] %>
#   password: <%= ENV['DBPASS'] %>
#   port: <%= ENV['DBPORT'] %>

# development:
#   <<: *default
#   database: SupermarketApi_development

# test:
#   <<: *default
#   database: SupermarketApi_test

# # production:
# #   <<: *default
# #   database: SupermarketApi_production
# #   username: SupermarketApi
# #   password: <%= ENV['SUPERMARKETAPI_DATABASE_PASSWORD'] %>



# default: &default
#   adapter: postgresql
#   encoding: unicode
#   # For details on connection pooling, see Rails configuration guide
#   # http://guides.rubyonrails.org/configuring.html#database-pooling
#   pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
#   host: <%= ENV['DBHOST'] %>
#   username: <%= ENV['DBUSER'] %>
#   password: <%= ENV['DBPASS'] %>
#   port: <%= ENV['DBPORT'] %>

# development:
#   <<: *default
#   database: SupermarketApi_development

# test:
#   <<: *default
#   database: SupermarketApi_test

# production:
#   <<: *default
#   database: SupermarketApi_production
#   username: SupermarketApi
#   password: <%= ENV['SUPERMARKETAPI_DATABASE_PASSWORD'] %>


default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: ec2-174-129-206-173.compute-1.amazonaws.com
  username: ywpcyzhjnjvijp
  password: 4cf76afea71979d9b97851282e046db9d189c991749c3602209b1ce4bd2d533c
  port: 5432

development:
  <<: *default
  database: d3vo4pnu00mdlk

test:
  <<: *default
  database: d3vo4pnu00mdlk

production:
  <<: *default
  database: d3vo4pnu00mdlk
  username: ywpcyzhjnjvijp
  password: <%= ENV['SUPERMARKETAPI_DATABASE_PASSWORD'] %>
